Import-Module (Join-Path $PSScriptRoot 'Repato.AgentOrchestration.psm1') -WarningAction SilentlyContinue
$script:DeployRegistry=Join-Path $PSScriptRoot 'DeploymentTargets.json'
function Get-DeploymentTargets{$r=Get-Content $script:DeployRegistry -Raw|ConvertFrom-Json;if($r.schemaVersion-ne1){throw 'Malformed deployment registry.'};$r}
function New-DeployPlan([string]$StoreRoot,[string]$TaskId,[string]$ArtifactPath,[string]$ManifestPath,[string]$TargetId,[switch]$DryRun){$root='C:\Repato-Autonomous\Source';$t=(Get-DeploymentTargets).targets|Where-Object targetId -ceq $TargetId;if(!$t-or$t.revit){throw 'Deployment target is not registered or is Revit.'};foreach($p in $ArtifactPath,$ManifestPath){$f=[IO.Path]::GetFullPath($p);if(!$f.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'Path escapes repository root.'};if(!(Test-Path $f)){throw "Missing artifact: $p"}};$a=(Get-FileHash $ArtifactPath -Algorithm SHA256).Hash;$m=(Get-FileHash $ManifestPath -Algorithm SHA256).Hash;[pscustomobject]@{schemaVersion=1;planId=[guid]::NewGuid().ToString('N');taskId=$TaskId;artifactPath=$ArtifactPath;artifactSha256=$a;manifestPath=$ManifestPath;manifestSha256=$m;targetId=$TargetId;targetPath=$t.path;mode=$(if($DryRun){'DryRun'}else{'Controlled'});sideEffectsPerformed=$false}}
function Invoke-Deploy([object]$Plan,[ValidateSet('deploy-backup','deploy-apply','deploy-verify','deploy-rollback')][string]$Operation='deploy-backup',[string]$TaskId,[string]$PlanId,[string]$ApprovalId,[switch]$DryRun){
 if($TaskId -and ($Plan.taskId -ne $TaskId -or $Plan.planId -ne $PlanId)){throw 'Deployment plan identity mismatch.'};if($ApprovalId){$null=Validate-DeployApproval $Plan $ApprovalId}
 if($Plan.targetId -ne 'qa-local-fixture'){throw 'Only the repository fixture target is permitted.'}
 $dir=Join-Path $PSScriptRoot 'DeploymentFixtures';$a=Join-Path $dir 'artifact.target';$m=Join-Path $dir 'manifest.target';$ab="$a.backup";$mb="$m.backup"
 if($DryRun){return [pscustomobject]@{Operation=$Operation;SideEffectsPerformed=$false;Target=$dir}}
 if($Plan.approvalStatus -and $Plan.approvalStatus -ne 'approved'){throw 'Missing or invalid deployment approval.'}
 if($Operation -eq 'deploy-backup'){Copy-Item $a $ab -Force;Copy-Item $m $mb -Force;return [pscustomobject]@{Operation=$Operation;ArtifactHash=(Get-FileHash $ab -Algorithm SHA256).Hash;ManifestHash=(Get-FileHash $mb -Algorithm SHA256).Hash}}
 if($Operation -eq 'deploy-apply'){if(!(Test-Path $ab)-or !(Test-Path $mb)){throw 'Backup required before apply.'};Copy-Item (Join-Path $dir 'artifact.source') "$a.tmp" -Force;Move-Item "$a.tmp" $a -Force;Copy-Item (Join-Path $dir 'manifest.source') "$m.tmp" -Force;Move-Item "$m.tmp" $m -Force;return [pscustomobject]@{Applied=$true;Operation=$Operation}}
 if($Operation -eq 'deploy-verify'){if((Get-FileHash $a -Algorithm SHA256).Hash -ne $Plan.artifactSha256 -or (Get-FileHash $m -Algorithm SHA256).Hash -ne $Plan.manifestSha256){Copy-Item $ab $a -Force;Copy-Item $mb $m -Force;throw 'Verification failed; automatic rollback completed.'};return [pscustomobject]@{Verified=$true}}
 if($Operation -eq 'deploy-rollback'){if(Test-Path $ab){Copy-Item $ab $a -Force};if(Test-Path $mb){Copy-Item $mb $m -Force};return [pscustomobject]@{RolledBack=$true;Idempotent=$true}}
}
function Get-DeployPlanHash([object]$Plan){$j=[ordered]@{taskId=$Plan.taskId;planId=$Plan.planId;artifactPath=$Plan.artifactPath;artifactSha256=$Plan.artifactSha256;manifestPath=$Plan.manifestPath;manifestSha256=$Plan.manifestSha256;targetId=$Plan.targetId;targetPath=$Plan.targetPath}|ConvertTo-Json -Compress;$h=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($h.ComputeHash([Text.Encoding]::UTF8.GetBytes($j)))).Replace('-','')}finally{$h.Dispose()}}
function Request-DeployApproval([string]$StoreRoot,[object]$Plan,[int]$ExpiryMinutes=30){$r=Request-RepatoTaskApproval $StoreRoot $Plan.taskId ('deployment:'+ $Plan.planId) maya $ExpiryMinutes;Invoke-RepatoStoreMutation $StoreRoot {param($d,$preview)$t=Find-RepatoTask $d $Plan.taskId;$q=@($t.approvalRequests|Where-Object action -eq ('deployment:'+ $Plan.planId))[-1];$q|Add-Member NoteProperty DeploymentPlanId $Plan.planId;$q|Add-Member NoteProperty PlanSha256 (Get-DeployPlanHash $Plan);$q|Add-Member NoteProperty ArtifactPath $Plan.artifactPath;$q|Add-Member NoteProperty ArtifactSha256 $Plan.artifactSha256;$q|Add-Member NoteProperty ManifestPath $Plan.manifestPath;$q|Add-Member NoteProperty ManifestSha256 $Plan.manifestSha256;$q|Add-Member NoteProperty TargetId $Plan.targetId;$q|Add-Member NoteProperty TargetPath $Plan.targetPath;$q|Add-Member NoteProperty RegistrySha256 (Get-FileHash $script:DeployRegistry -Algorithm SHA256).Hash;$q|Add-Member NoteProperty Nonce ([guid]::NewGuid().ToString('N'));$q}}
function Validate-DeployApproval([string]$StoreRoot,[object]$Plan,[string]$ApprovalId){$d=Read-RepatoTaskStore $StoreRoot;$t=Find-RepatoTask $d $Plan.taskId;$q=@($t.approvalRequests|Where-Object requestId -ceq $ApprovalId)[0];if(!$q-or$q.status-ne'approved'-or$q.consumedUtc-or$q.PlanSha256-cne(Get-DeployPlanHash $Plan)-or$q.approvedRevision-ne$t.revision){throw 'Deployment approval invalid or stale.'};$q}
function Consume-DeployApproval([string]$StoreRoot,[string]$TaskId,[string]$ApprovalId){Invoke-RepatoStoreMutation $StoreRoot {param($d,$preview)$t=Find-RepatoTask $d $TaskId;$q=@($t.approvalRequests|Where-Object requestId -ceq $ApprovalId)[0];if(!$q-or$q.consumedUtc){throw 'Deployment approval missing or already consumed.'};$q.consumedUtc=Get-RepatoUtc;$q.status='consumed';Add-RepatoHistory $t 'deployment-approval-consumed' 'Maya' "approval=$ApprovalId";$q}}
function Get-DeployStatus([string]$StoreRoot,[string]$TaskId){[pscustomobject]@{TaskId=$TaskId;Status='dry-run-only';Deployments=@()}}
Export-ModuleMember -Function Get-DeploymentTargets,New-DeployPlan,Request-DeployApproval,Validate-DeployApproval,Consume-DeployApproval,Invoke-Deploy,Get-DeployStatus

# Fixture executor operations are intentionally limited to qa-local-fixture and remain dry-run by default.