Import-Module (Join-Path $PSScriptRoot 'Repato.AgentOrchestration.psm1') -Force -WarningAction SilentlyContinue
Import-Module (Join-Path $PSScriptRoot 'Repato.ProcessSupervisor.psm1') -Force -WarningAction SilentlyContinue
function Initialize-Joint([object]$Task){if($Task.PSObject.Properties.Name -notcontains 'jointApprovals'){$Task|Add-Member -MemberType NoteProperty -Name jointApprovals -Value @()}}
function Get-Joint([object]$Task,[string]$ApprovalId){Initialize-Joint $Task;$a=@($Task.jointApprovals|Where-Object approvalId -ceq $ApprovalId);if($a.Count-ne1){throw "Joint approval '$ApprovalId' was not found."};$a[0]}
function Get-AdapterIdentity([object]$Task,[object]$Run){if($Run.adapterId-eq'tara.run'){$inner=@($Task.taraRuns|Where-Object runId -ceq $Run.adapterRunId)[0];$cmd=$inner.commandSha256}else{$inner=@($Task.neilRuns|Where-Object runId -ceq $Run.adapterRunId)[0];$cmd=$inner.actionSha256};if(!$inner){throw 'Underlying adapter run is missing.'};[pscustomobject]@{AdapterPlanSha256=$inner.planSha256;AdapterRegistrySha256=$inner.registrySha256;CommandSha256=$cmd}}
function New-JointPlan([string]$StoreRoot,[string]$TaskId,[string]$AdapterId,[switch]$DryRun){$p=New-SupervisorPlan $StoreRoot $TaskId $AdapterId 60 -DryRun:$DryRun;$d=Read-RepatoTaskStore $StoreRoot;$t=Find-RepatoTask $d $TaskId;$r=@($t.supervisorRuns|Where-Object runId -ceq $p.runId)[0];$i=Get-AdapterIdentity $t $r;[pscustomobject]@{SchemaVersion=1;Mode=$(if($DryRun){'DryRun'}else{'Controlled'});TaskId=$TaskId;SupervisorExecutionId=$p.runId;AdapterId=$r.adapterId;OperationId=$r.operation;AdapterRunId=$r.adapterRunId;TaskRevision=[long]$t.revision;PlanSha256=$r.planSha256;AdapterPlanSha256=$i.AdapterPlanSha256;AdapterRegistrySha256=$i.AdapterRegistrySha256;CommandSha256=$i.CommandSha256;SideEffectsPerformed=$false}}
function Request-JointApproval([string]$StoreRoot,[string]$TaskId,[string]$SupervisorExecutionId,[int]$ExpiryMinutes=30){Invoke-RepatoStoreMutation $StoreRoot {param($d,$preview)$t=Find-RepatoTask $d $TaskId;Initialize-Joint $t; $r=@($t.supervisorRuns|Where-Object runId -ceq $SupervisorExecutionId)[0];if(!$r){throw 'Supervisor execution not found.'};$i=Get-AdapterIdentity $t $r;if(@($t.jointApprovals|Where-Object status -eq 'pending').Count){throw 'A joint approval is already pending.'};$q=[pscustomobject]@{schemaVersion=1;approvalId=[guid]::NewGuid().ToString('N');nonce=[guid]::NewGuid().ToString('N');taskId=$TaskId;supervisorExecutionId=$SupervisorExecutionId;adapterId=$r.adapterId;operationId=$r.operation;adapterRunId=$r.adapterRunId;taskRevision=[long]$t.revision;planSha256=$r.planSha256;adapterPlanSha256=$i.AdapterPlanSha256;adapterRegistrySha256=$i.AdapterRegistrySha256;commandSha256=$i.CommandSha256;requiredLevel='maya';status='pending';requestedUtc=Get-RepatoUtc;expiresUtc=[DateTimeOffset]::UtcNow.AddMinutes($ExpiryMinutes).ToString('O');approvedRevision=$null;consumedUtc=$null};$t.jointApprovals=[object[]]@($t.jointApprovals)+$q;Add-RepatoHistory $t 'joint-approval-requested' 'Maya' "execution=$SupervisorExecutionId";$q}}
function Validate-JointApproval([string]$StoreRoot,[string]$TaskId,[string]$ApprovalId){$d=Read-RepatoTaskStore $StoreRoot;$t=Find-RepatoTask $d $TaskId;$q=Get-Joint $t $ApprovalId;$r=@($t.supervisorRuns|Where-Object runId -ceq $q.supervisorExecutionId)[0];if(!$r){throw 'Joint supervisor execution is missing.'};$i=Get-AdapterIdentity $t $r;if($q.taskId-cne$TaskId-or$q.adapterId-cne$r.adapterId-or$q.operationId-cne$r.operation-or$q.adapterRunId-cne$r.adapterRunId-or$q.planSha256-cne$r.planSha256-or$q.adapterPlanSha256-cne$i.AdapterPlanSha256-or$q.adapterRegistrySha256-cne$i.AdapterRegistrySha256-or$q.commandSha256-cne$i.CommandSha256-or$q.status-cne'approved'-or$q.consumedUtc-or[DateTimeOffset]::Parse($q.expiresUtc)-le[DateTimeOffset]::UtcNow-or[long]$q.approvedRevision-ne[long]$t.revision){throw 'Joint approval identity, revision, expiry, or nonce is invalid.'};$q}
function Get-JointPreview([string]$StoreRoot,[string]$TaskId,[string]$ApprovalId){$q=Validate-JointApproval $StoreRoot $TaskId $ApprovalId;[pscustomobject]@{Mode='DryRun';TaskId=$TaskId;ApprovalId=$ApprovalId;SupervisorExecutionId=$q.supervisorExecutionId;AdapterId=$q.adapterId;OperationId=$q.operationId;AdapterRunId=$q.adapterRunId;PlanSha256=$q.planSha256;CommandSha256=$q.commandSha256;SideEffectsPerformed=$false}}
function Start-JointExecution([string]$StoreRoot,[string]$TaskId,[string]$ApprovalId,[switch]$DryRun){if($DryRun){return Get-JointPreview $StoreRoot $TaskId $ApprovalId};throw 'Real joint process execution is disabled; use -DryRun.'}
function Reconcile-Joint([string]$StoreRoot,[string]$TaskId){Get-SupervisorStatus $StoreRoot $TaskId}
function Fail-Joint([string]$StoreRoot,[string]$TaskId,[string]$ApprovalId,[string]$ErrorDetails){if([string]::IsNullOrWhiteSpace($ErrorDetails)){throw 'Failure details required.'};Invoke-RepatoStoreMutation $StoreRoot {param($d,$p)$t=Find-RepatoTask $d $TaskId;$q=Get-Joint $t $ApprovalId;$q.status='failed';$q.errorDetails=$ErrorDetails;Add-RepatoHistory $t 'joint-failed' 'Maya' $ErrorDetails;$q}}
Export-ModuleMember -Function New-JointPlan,Request-JointApproval,Validate-JointApproval,Get-JointPreview,Start-JointExecution,Reconcile-Joint,Fail-Joint