Import-Module (Join-Path $PSScriptRoot 'Repato.AgentOrchestration.psm1') -WarningAction SilentlyContinue

$script:NeilRepositoryRoot='C:\Repato-Autonomous\Source'
$script:NeilRegistryPath=Join-Path $PSScriptRoot 'NeilActions.json'
$script:NeilLogsRoot=Join-Path $PSScriptRoot 'Logs'
$script:NeilFixturePath='AgentOrchestration/Fixtures/NeilAdapterTarget.txt'

function Get-NeilSha256Bytes([byte[]]$Bytes){$algorithm=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($algorithm.ComputeHash($Bytes))).Replace('-','')}finally{$algorithm.Dispose()}}
function Get-NeilSha256Text([string]$Text){Get-NeilSha256Bytes ([Text.Encoding]::UTF8.GetBytes($Text))}
function Assert-NeilRepositoryPath([string]$Path,[bool]$MustExist=$true){
    if([string]::IsNullOrWhiteSpace($Path)-or$Path-notmatch'^[A-Za-z]:\\'-or$Path.Substring(2).Contains(':')){throw 'Absolute local repository path required.'}
    $full=[IO.Path]::GetFullPath($Path);$root=[IO.Path]::GetFullPath($script:NeilRepositoryRoot).TrimEnd([IO.Path]::DirectorySeparatorChar)+[IO.Path]::DirectorySeparatorChar
    if(!$full.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw "Path escapes repository root: $full"}
    if($MustExist-and!(Test-Path -LiteralPath $full -PathType Leaf)){throw "Registered edit target is missing: $full"};$full
}
function Get-NeilCurrentBranch {
    $gitPath=Join-Path $script:NeilRepositoryRoot '.git';$headPath=if(Test-Path $gitPath -PathType Container){Join-Path $gitPath 'HEAD'}else{$line=Get-Content $gitPath -Raw;if($line-notmatch'^gitdir:\s*(.+)$'){throw 'Malformed Git worktree pointer.'};Join-Path ([IO.Path]::GetDirectoryName($gitPath)) (Join-Path $Matches[1].Trim() 'HEAD')}
    $head=(Get-Content -LiteralPath $headPath -Raw).Trim();if($head-notmatch'^ref: refs/heads/(.+)$'){throw 'Detached or malformed Git HEAD is not allowed.'};$Matches[1]
}
function Read-NeilDocument([string]$Path){
    $bytes=[IO.File]::ReadAllBytes($Path);$bom=$bytes.Length-ge3-and$bytes[0]-eq0xEF-and$bytes[1]-eq0xBB-and$bytes[2]-eq0xBF;$offset=if($bom){3}else{0}
    $utf8=[Text.UTF8Encoding]::new($false,$true);try{$text=$utf8.GetString($bytes,$offset,$bytes.Length-$offset)}catch{throw "Registered edit target is not valid UTF-8: $Path"}
    [pscustomobject]@{Path=$Path;Bytes=$bytes;Text=$text;HasBom=$bom;Sha256=Get-NeilSha256Bytes $bytes;LastWriteUtc=([IO.File]::GetLastWriteTimeUtc($Path).ToString('O'))}
}
function ConvertTo-NeilBytes([string]$Text,[bool]$HasBom){$body=[Text.UTF8Encoding]::new($false).GetBytes($Text);if(!$HasBom){return $body};$preamble=[Text.Encoding]::UTF8.GetPreamble();$all=[byte[]]::new($preamble.Length+$body.Length);[Array]::Copy($preamble,0,$all,0,$preamble.Length);[Array]::Copy($body,0,$all,$preamble.Length,$body.Length);$all}
function Get-NeilDiff([string]$RelativePath,[string]$Before,[string]$After){
    $old=@($Before -split "`r?`n",-1);$new=@($After -split "`r?`n",-1);$lines=@("--- a/$RelativePath","+++ b/$RelativePath","@@ -1,$($old.Count) +1,$($new.Count) @@");$lines+=@($old|ForEach-Object{'-'+$_});$lines+=@($new|ForEach-Object{'+'+$_});$lines-join"`n"
}
function Get-NeilRegistry {
    $path=Assert-NeilRepositoryPath $script:NeilRegistryPath
    try{$registry=Get-Content -LiteralPath $path -Raw|ConvertFrom-Json}catch{throw "Malformed Neil action registry: $($_.Exception.Message)"}
    if($registry.schemaVersion-ne1-or$registry.repositoryRoot-ine$script:NeilRepositoryRoot-or$registry.productionFiles-isnot[Array]-or$registry.actions-isnot[Array]){throw 'Invalid Neil action registry.'}
    $files=@{};foreach($relative in $registry.productionFiles){if($relative-notmatch'^[A-Za-z0-9._-]+\.cs$'-or$relative.Contains('..')-or$files.ContainsKey($relative)){throw 'Unsafe or duplicate registered production file.'};$files[$relative]=Assert-NeilRepositoryPath (Join-Path $script:NeilRepositoryRoot $relative)}
    $actions=@{};foreach($action in $registry.actions){
        if($action.actionId-notmatch'^[a-z0-9][a-z0-9.-]{2,95}$'-or$actions.ContainsKey($action.actionId)-or$action.targetPath.Contains('..')-or$action.replacements-isnot[Array]){throw 'Unsafe, duplicate, or malformed registered Neil action.'}
        $isTest=[bool]$action.testOnly;if($isTest){if($action.targetPath-cne$script:NeilFixturePath){throw 'Test action target is not the controlled Neil fixture.'}}elseif(!$files.ContainsKey([string]$action.targetPath)){throw 'Production action target is not an explicitly registered production file.'}
        $target=Assert-NeilRepositoryPath (Join-Path $script:NeilRepositoryRoot ([string]$action.targetPath).Replace('/','\'))
        foreach($replacement in @($action.replacements)){if([string]::IsNullOrEmpty($replacement.oldText)-or$replacement.oldText-ceq$replacement.newText){throw 'Neil replacement must be a nonempty exact transformation.'}}
        $identity=[ordered]@{actionId=$action.actionId;targetPath=$action.targetPath;testOnly=$isTest;description=$action.description;replacements=@($action.replacements)}|ConvertTo-Json -Depth 8 -Compress
        $actions[$action.actionId]=[pscustomobject]@{ActionId=$action.actionId;TargetPath=$target;RelativePath=$action.targetPath;TestOnly=$isTest;Description=$action.description;Replacements=@($action.replacements);ActionSha256=Get-NeilSha256Text $identity}
    }
    [pscustomobject]@{Path=$path;Sha256=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash;ProductionFiles=$files;Actions=$actions}
}
function Resolve-NeilAction($Definition){
    $document=Read-NeilDocument $Definition.TargetPath;$after=$document.Text
    foreach($replacement in $Definition.Replacements){$count=[regex]::Matches($after,[regex]::Escape([string]$replacement.oldText)).Count;if($count-ne1){throw "Registered replacement expected exactly one match; found $count."};$after=$after.Replace([string]$replacement.oldText,[string]$replacement.newText)}
    $afterBytes=ConvertTo-NeilBytes $after $document.HasBom
    [pscustomobject]@{Document=$document;AfterText=$after;AfterBytes=$afterBytes;AfterSha256=Get-NeilSha256Bytes $afterBytes;Diff=Get-NeilDiff $Definition.RelativePath $document.Text $after}
}
function Get-NeilPlanHash($Run){$value=[ordered]@{actionId=$Run.actionId;targetPath=$Run.targetPath;registrySha256=$Run.registrySha256;actionSha256=$Run.actionSha256;beforeSha256=$Run.beforeSha256;afterSha256=$Run.afterSha256;branchName=$Run.branchName;plannedRevision=$Run.plannedRevision}|ConvertTo-Json -Compress;Get-NeilSha256Text $value}
function Initialize-NeilRuns($Task){if($Task.PSObject.Properties.Name-notcontains'neilRuns'){$Task|Add-Member -NotePropertyName neilRuns -NotePropertyValue ([object[]]@())}}
function Find-NeilRun($Task,[string]$RunId){Initialize-NeilRuns $Task;$runs=@($Task.neilRuns|Where-Object runId -ceq $RunId);if($runs.Count-ne1){throw "Neil run not found: $RunId"};$runs[0]}
function Assert-NeilTask($Task){Assert-RepatoTask $Task;if($Task.assignedAgent-cne'Neil'){throw 'Task must be assigned to Neil.'};if($Task.status-cne'in-progress'-or$Task.workflowStage-cne'implementation'){throw 'Neil edits require an in-progress implementation-stage task.'};$branch=Get-NeilCurrentBranch;if($Task.branchName-cne$branch){throw "Task branch $($Task.branchName) does not match current branch $branch."}}

function New-NeilPlan([string]$StoreRoot,[string]$TaskId,[string]$ActionId,[switch]$DryRun){
    Invoke-RepatoStoreMutation $StoreRoot {param($data,$preview)$task=Find-RepatoTask $data $TaskId;Assert-NeilTask $task;Initialize-NeilRuns $task;$registry=Get-NeilRegistry
        if(!$registry.Actions.ContainsKey($ActionId)){throw "Unknown Neil action: $ActionId"};if(@($task.neilRuns|Where-Object status -in @('planned','validated','running')).Count){throw 'An active Neil run already exists for this task.'};$action=$registry.Actions[$ActionId];$resolved=Resolve-NeilAction $action
        $run=[pscustomobject][ordered]@{runId=[guid]::NewGuid().ToString('N');actionId=$ActionId;status='planned';targetPath=$action.RelativePath;testOnly=$action.TestOnly;description=$action.Description;branchName=$task.branchName;registrySha256=$registry.Sha256;actionSha256=$action.ActionSha256;beforeSha256=$resolved.Document.Sha256;afterSha256=$resolved.AfterSha256;diff=$resolved.Diff;planSha256='';plannedRevision=[long]0;validatedRevision=$null;plannedUtc=Get-RepatoUtc;startedUtc=$null;finishedUtc=$null;beforeLastWriteUtc=$resolved.Document.LastWriteUtc;afterLastWriteUtc=$null;changedFiles=[object[]]@();logPath=$null;errorDetails=$null};if(!$preview){$task.neilRuns=[object[]]@($task.neilRuns)+$run;Add-RepatoHistory $task 'neil-planned' 'Maya' "run=$($run.runId); action=$ActionId";$run.plannedRevision=[long]$task.revision};$run.planSha256=Get-NeilPlanHash $run;$run
    } -DryRun:$DryRun
}
function Test-NeilPlan([string]$StoreRoot,[string]$TaskId,[string]$RunId,[switch]$DryRun){
    Invoke-RepatoStoreMutation $StoreRoot {param($data,$preview)$task=Find-RepatoTask $data $TaskId;Assert-NeilTask $task;$run=Find-NeilRun $task $RunId;if($run.status -notin @('planned','validated')){throw 'Neil run cannot be validated in its current state.'};if($run.status-cne'validated'-and[long]$run.plannedRevision-ne[long]$task.revision){throw 'Task changed after Neil planning.'};$registry=Get-NeilRegistry;if(!$registry.Actions.ContainsKey($run.actionId)){throw 'Neil action is no longer registered.'};$action=$registry.Actions[$run.actionId];$resolved=Resolve-NeilAction $action
        if($run.targetPath-cne$action.RelativePath-or$run.registrySha256-cne$registry.Sha256-or$run.actionSha256-cne$action.ActionSha256-or$run.beforeSha256-cne$resolved.Document.Sha256-or$run.afterSha256-cne$resolved.AfterSha256-or$run.diff-cne$resolved.Diff-or$run.branchName-cne$task.branchName-or(Get-NeilPlanHash $run)-cne$run.planSha256){throw 'Neil plan, file identity, branch, or registry changed.'}
        if(!$preview-and$run.status-cne'validated'){$run.status='validated';Add-RepatoHistory $task 'neil-validated' 'Neil' "run=$RunId; hash=$($run.planSha256)";$run.validatedRevision=[long]$task.revision};[pscustomobject]@{TaskId=$TaskId;RunId=$RunId;Valid=$true;ActionId=$run.actionId;PlanSha256=$run.planSha256;TaskRevision=$task.revision}
    } -DryRun:$DryRun
}
function Request-NeilApproval([string]$StoreRoot,[string]$TaskId,[string]$RunId,[int]$ExpiryMinutes=30,[switch]$DryRun){
    Invoke-RepatoStoreMutation $StoreRoot {param($data,$preview)$task=Find-RepatoTask $data $TaskId;$run=Find-NeilRun $task $RunId;if($run.status-cne'validated'-or[long]$run.validatedRevision-ne[long]$task.revision){throw 'Neil run must be freshly validated before approval.'};if(@($task.approvalRequests|Where-Object status -ceq 'pending').Count){throw 'Task already has a pending approval.'};$request=[pscustomobject]@{requestId=[guid]::NewGuid().ToString('N');action=('neil-apply:'+$run.actionId);requiredLevel='maya';status='pending';bindingHash=$run.planSha256;previousStatus=$task.status;requestedRevision=[long]0;approvedRevision=$null;requestedUtc=Get-RepatoUtc;expiresUtc=[DateTimeOffset]::UtcNow.AddMinutes($ExpiryMinutes).ToString('O');decidedUtc=$null;decidedBy=$null;reason=$null;consumedUtc=$null};if(!$preview){$task.approvalRequests=[object[]]@($task.approvalRequests)+$request;$task.status='awaiting-approval';Add-RepatoHistory $task 'neil-approval-requested' 'Maya' "run=$RunId";$request.requestedRevision=[long]$task.revision};$request
    } -DryRun:$DryRun
}
function Assert-NeilApproval($Task,$Run){$matches=@($Task.approvalRequests|Where-Object{$_.action-ceq('neil-apply:'+$Run.actionId)-and$_.bindingHash-ceq$Run.planSha256-and$_.status-ceq'approved'-and$null-eq$_.consumedUtc});if($matches.Count-ne1){throw 'Missing or mismatched Neil edit approval.'};$approval=$matches[0];if([DateTimeOffset]::Parse($approval.expiresUtc)-le[DateTimeOffset]::UtcNow-or[long]$approval.approvedRevision-ne[long]$Task.revision){throw 'Neil edit approval expired or task changed after approval.'};$approval}
function Get-NeilPreview([string]$StoreRoot,[string]$TaskId,[string]$RunId){$paths=Get-RepatoStorePaths $StoreRoot;$lock=$null;try{$lock=[IO.File]::Open($paths.Lock,[IO.FileMode]::OpenOrCreate,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None);$data=Read-RepatoTaskStore $StoreRoot;$task=Find-RepatoTask $data $TaskId;$run=Find-NeilRun $task $RunId;if($run.status-cne'validated'){throw 'Neil run is not validated.'};$null=Assert-NeilApproval $task $run;[pscustomobject]@{TaskId=$TaskId;RunId=$RunId;Mode='DryRun';ActionId=$run.actionId;ChangedFiles=@($run.targetPath);BeforeSha256=$run.beforeSha256;AfterSha256=$run.afterSha256;Diff=$run.diff;SideEffectsPerformed=$false;ApprovalCheckedUtc=Get-RepatoUtc}}finally{if($lock){$lock.Dispose()}}}
function Write-NeilFileAtomic([string]$Path,[byte[]]$Bytes){$temporary=$Path+'.'+[guid]::NewGuid().ToString('N')+'.partial';try{[IO.File]::WriteAllBytes($temporary,$Bytes);Move-Item -LiteralPath $temporary -Destination $Path -Force}finally{if(Test-Path $temporary){Remove-Item -LiteralPath $temporary -Force}}}

function Invoke-NeilApply([string]$StoreRoot,[string]$TaskId,[string]$RunId,[switch]$DryRun){
    if($DryRun){return Get-NeilPreview $StoreRoot $TaskId $RunId}
    $start=Invoke-RepatoStoreMutation $StoreRoot {param($data,$preview)$task=Find-RepatoTask $data $TaskId;if($task.assignedAgent-cne'Neil'-or$task.workflowStage-cne'implementation'){throw 'Neil run is not executable.'};$run=Find-NeilRun $task $RunId;if($run.status-cne'validated'){throw 'Neil run is not executable.'};$registry=Get-NeilRegistry;if(!$registry.Actions.ContainsKey($run.actionId)){throw 'Neil action is no longer registered.'};$action=$registry.Actions[$run.actionId];$resolved=Resolve-NeilAction $action
        if((Get-NeilCurrentBranch)-cne$run.branchName-or$run.registrySha256-cne$registry.Sha256-or$run.actionSha256-cne$action.ActionSha256-or$run.beforeSha256-cne$resolved.Document.Sha256-or$run.afterSha256-cne$resolved.AfterSha256-or$run.diff-cne$resolved.Diff-or(Get-NeilPlanHash $run)-cne$run.planSha256){throw 'Neil execution identity, branch, registry, or source changed.'};$approval=Assert-NeilApproval $task $run;$approval.consumedUtc=Get-RepatoUtc;$run.status='running';$run.startedUtc=Get-RepatoUtc;Add-RepatoHistory $task 'neil-started' 'Neil' "run=$RunId; action=$($run.actionId)";[pscustomobject]@{ActionId=$run.actionId;TargetPath=$action.TargetPath;RelativePath=$action.RelativePath;BeforeSha256=$run.beforeSha256;AfterSha256=$run.afterSha256;BeforeBytes=$resolved.Document.Bytes;Diff=$run.diff;AfterBytes=$resolved.AfterBytes;StartedUtc=$run.startedUtc}
    }
    $watch=[Diagnostics.Stopwatch]::StartNew();$errorText=$null;$changed=$false;$beforeTime=[IO.File]::GetLastWriteTimeUtc($start.TargetPath).ToString('O')
    try{$current=Read-NeilDocument $start.TargetPath;if($current.Sha256-cne$start.BeforeSha256){throw 'Source changed immediately before the approved atomic edit.'};Write-NeilFileAtomic $start.TargetPath $start.AfterBytes;$written=Read-NeilDocument $start.TargetPath;if($written.Sha256-cne$start.AfterSha256){Write-NeilFileAtomic $start.TargetPath $start.BeforeBytes;throw 'Written file hash did not match the approved result; the original bytes were restored.'};$changed=$true;$afterTime=$written.LastWriteUtc}catch{$errorText=$_.Exception.ToString();$afterTime=if(Test-Path $start.TargetPath){[IO.File]::GetLastWriteTimeUtc($start.TargetPath).ToString('O')}else{$null}}finally{$watch.Stop()}
    $finished=Get-RepatoUtc;New-Item -ItemType Directory -Path $script:NeilLogsRoot -Force|Out-Null;$logPath=Join-Path $script:NeilLogsRoot ($TaskId+'-'+$RunId+'.neil.json');$record=[ordered]@{schemaVersion=1;taskId=$TaskId;runId=$RunId;actionId=$start.ActionId;startedUtc=$start.StartedUtc;finishedUtc=$finished;durationMilliseconds=$watch.Elapsed.TotalMilliseconds;changedFiles=$(if($changed){@($start.RelativePath)}else{@()});beforeSha256=$start.BeforeSha256;afterSha256=$(if($changed){$start.AfterSha256}else{$null});beforeLastWriteUtc=$beforeTime;afterLastWriteUtc=$afterTime;diff=$start.Diff;errorDetails=$errorText};Write-RepatoJsonAtomic $logPath $record
    Invoke-RepatoStoreMutation $StoreRoot {param($data,$preview)$task=Find-RepatoTask $data $TaskId;$run=Find-NeilRun $task $RunId;if($run.status-cne'running'){throw 'Neil run state changed during editing.'};$run.status=$(if($changed){'passed'}else{'failed'});$run.finishedUtc=$finished;$run.afterLastWriteUtc=$afterTime;$run.changedFiles=$(if($changed){[object[]]@($start.RelativePath)}else{[object[]]@()});$run.logPath=$logPath;$run.errorDetails=$errorText;$task.logs=[object[]]@($task.logs)+$logPath;if(!$changed){$task.status='failed';$task.finishedUtc=$finished;$task.errorDetails=$errorText};Add-RepatoHistory $task ('neil-'+$run.status) 'Neil' "run=$RunId; log=$logPath";$run}
}
function Fail-NeilRun([string]$StoreRoot,[string]$TaskId,[string]$RunId,[string]$ErrorDetails,[switch]$DryRun){if([string]::IsNullOrWhiteSpace($ErrorDetails)){throw 'Failure details are required.'};Invoke-RepatoStoreMutation $StoreRoot {param($data,$preview)$task=Find-RepatoTask $data $TaskId;$run=Find-NeilRun $task $RunId;if($run.status -in @('passed','failed')){throw 'Neil run is terminal.'};if(!$preview){$run.status='failed';$run.finishedUtc=Get-RepatoUtc;$run.errorDetails=$ErrorDetails;$task.status='failed';$task.finishedUtc=$run.finishedUtc;$task.errorDetails=$ErrorDetails;Add-RepatoHistory $task 'neil-failed' 'Neil' "run=$RunId; $ErrorDetails"};$run} -DryRun:$DryRun}

Export-ModuleMember -Function New-NeilPlan,Test-NeilPlan,Request-NeilApproval,Get-NeilPreview,Invoke-NeilApply,Fail-NeilRun,Get-NeilRegistry