$ErrorActionPreference='Stop'; Import-Module (Join-Path $PSScriptRoot 'Repato.AgentOrchestration.psm1') -Force; Import-Module (Join-Path $PSScriptRoot 'Repato.Deployment.v4.psm1') -Force; Import-Module (Join-Path $PSScriptRoot 'Repato.MayaQaWorkflow.psm1') -Force
$defs=@('welcome-smoke','create-grids-world-axis-v1','create-levels','grid-bubble-visibility-v1','grid-bubble-offset-v1','grid-resequence-v1'); foreach($id in $defs){if(!(Get-MayaQaWorkflowDefinition $id)){throw "Missing definition: $id"}}
try {
    $root=Join-Path $env:TEMP ('maya-qa-coordinator-'+[guid]::NewGuid().ToString('N'));$store=Join-Path $root 'store';$target=Join-Path $root 'target';$runtime=Join-Path $root 'runtime';New-Item -ItemType Directory -Path $target|Out-Null
    $artifact=Join-Path $target 'artifact.bin';$manifest=Join-Path $target 'manifest.addin';Set-Content $artifact 'artifact';Set-Content $manifest 'manifest'
    $taskId='qa-coordinator-'+[guid]::NewGuid().ToString('N').Substring(0,12);New-RepatoTask $store $taskId 'QA coordinator' 'fixture test' 'feat/test'|Out-Null
    $plan=New-DeployPlan $store $taskId $artifact $manifest -TargetRoot $target;$w=New-DeployWorkflow $store $plan
    $d=Read-RepatoTaskStore $store;$t=Find-RepatoTask $d $taskId;$e=@(Invoke-RepatoWorkflowMutation $store $TaskId $w.workflowId $w.workflowRevision $t.revision {param($x)$x|Add-Member -NotePropertyName qaBuildStatus -NotePropertyValue 'succeeded' -Force;$x|Add-Member -NotePropertyName qaBuildEvidence -NotePropertyValue ([pscustomobject]@{ArtifactPath=$artifact;ArtifactSha256=(Get-FileHash $artifact -Algorithm SHA256).Hash;ManifestPath=$manifest;ManifestSha256=(Get-FileHash $manifest -Algorithm SHA256).Hash;SourceBranch='feat/test';CommitId='synthetic';BuildStatus='succeeded'}) -Force;return $x})[-1];$w=$e.Workflow
    $runId='run-'+[guid]::NewGuid().ToString('N').Substring(0,8);$run=New-MayaQaRun $store $taskId $w.workflowId 'create-levels' $runId -RuntimeRoot $runtime;if($run.FixtureId -ne 'CreateLevelsEmpty' -or !(Test-Path $run.SidecarPath)){throw 'QA run preparation failed.'};$runtimeRun=Join-Path $runtime ($w.workflowId+'-'+$runId);if(!(Test-Path -LiteralPath $runtimeRun -PathType Container)){throw 'Synthetic runtime folder was not created.'};$runtimeProbe=Join-Path $runtimeRun 'runtime-write.probe';Set-Content -LiteralPath $runtimeProbe -Value 'synthetic';if((Get-Content -LiteralPath $runtimeProbe -Raw).Trim() -ne 'synthetic'){throw 'Synthetic runtime folder was not writable.'}
    $reportRoot=Join-Path $root 'reports';New-Item -ItemType Directory -Path $reportRoot -Force|Out-Null;$reportPath=Join-Path $reportRoot ('synthetic-'+[guid]::NewGuid().ToString('N')+'.json');$report=[ordered]@{SchemaVersion='1';RunId=([guid]::NewGuid().ToString('N'));TestId='create-levels-elevations-v1';Status='Passed';DocumentPath=$run.ModelPath;FixtureId=$run.FixtureId;FixtureSha256=$run.FixtureSha256;Assertions=@([pscustomobject]@{Id='synthetic';Passed=$true});RollbackStatus='RolledBack';StartedUtc=(Get-Date).ToUniversalTime().ToString('O');FinishedUtc=(Get-Date).ToUniversalTime().AddSeconds(1).ToString('O')};$report|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $reportPath -Encoding UTF8;$verified=Register-MayaQaReport $store $taskId $w.workflowId 'create-levels' $reportPath -ReportRoot $reportRoot;if(!$verified.Valid){throw 'Independent native RunId report was rejected.'};$reloaded=Get-DeployWorkflow $store $taskId $w.workflowId;if($reloaded.qaEvidence.CoordinatorRunId -ne $run.RunId -or $reloaded.qaEvidence.NativeRunId -ne $report.RunId){throw 'Report run identities were not persisted separately.'}
    $rejected=$false;try{Get-MayaQaWorkflowDefinition 'wrong-id'|Out-Null}catch{$rejected=$true};if(!$rejected){throw 'Wrong ID accepted.'}
    $d=Read-RepatoTaskStore $store;$t=Find-RepatoTask $d $taskId;$current=Get-DeployWorkflow $store $taskId $w.workflowId;$removed=@(Invoke-RepatoWorkflowMutation $store $taskId $w.workflowId $current.workflowRevision $t.revision {param($x)$x.PSObject.Properties.Remove('qaVerificationStatus');$x.PSObject.Properties.Remove('qaCompletionStatus');$x.PSObject.Properties.Remove('qaCompletedUtc');return $x})[-1]
    $reportBytes=[IO.File]::ReadAllBytes($reportPath);[IO.File]::AppendAllText($reportPath,'stale');$staleRejected=$false;try{Complete-MayaQaWorkflow $store $taskId $w.workflowId|Out-Null}catch{$staleRejected=$true};if(!$staleRejected){throw 'Stale evidence was accepted.'};[IO.File]::WriteAllBytes($reportPath,$reportBytes)
    $completed=Complete-MayaQaWorkflow $store $taskId $w.workflowId;if($completed.QaCompletionStatus -ne 'completed' -or !$completed.CoordinatorRunId -or !$completed.NativeRunId){throw 'QA completion evidence was not persisted.'};$duplicateRejected=$false;try{Complete-MayaQaWorkflow $store $taskId $w.workflowId|Out-Null}catch{$duplicateRejected=$true};if(!$duplicateRejected){throw 'Duplicate completion was accepted.'};$reportBytes=[IO.File]::ReadAllBytes($reportPath);[IO.File]::AppendAllText($reportPath,'mismatch');$hashRejected=$false;try{New-MayaQaReceipt $store $taskId $w.workflowId -ReportRoot $reportRoot|Out-Null}catch{$hashRejected=$true};if(!$hashRejected){throw 'Receipt hash mismatch was accepted.'};[IO.File]::WriteAllBytes($reportPath,$reportBytes);$receipt=New-MayaQaReceipt $store $taskId $w.workflowId -ReportRoot $reportRoot;if(!$receipt.FinalReceiptSha256 -or $receipt.Duplicate){throw 'Receipt generation failed.'};$duplicateReceipt=New-MayaQaReceipt $store $taskId $w.workflowId -ReportRoot $reportRoot;if(!$duplicateReceipt.Duplicate -or $duplicateReceipt.FinalReceiptSha256 -ne $receipt.FinalReceiptSha256){throw 'Duplicate receipt was not idempotent.'};Remove-Item -LiteralPath $reportPath -Force;Remove-Item -LiteralPath $receipt.ReceiptPath -Force
    $dry=New-MayaQaRun $store $taskId $w.workflowId 'create-levels' 'dry-run' -DryRun;if($dry.SideEffectsPerformed){throw 'Dry-run performed side effects.'}
    'Maya QA workflow coordinator checks passed: 14'
} finally { if($root -and (Test-Path $root)){Remove-Item $root -Recurse -Force};if($root -and (Test-Path $root)){throw 'Synthetic runtime cleanup failed.'} }
