$ErrorActionPreference='Stop';$h=$PSScriptRoot;Import-Module (Join-Path $h 'Repato.AgentOrchestration.psm1') -Force -WarningAction SilentlyContinue
$run=Join-Path ([IO.Path]::GetTempPath()) ('maya-v4-cli-'+[guid]::NewGuid().ToString('N'));$target=Join-Path $run 'target';$store=Join-Path $run 'store';New-Item $target -ItemType Directory -Force|Out-Null;$fx=Join-Path $h 'DeploymentFixtures';foreach($n in @('artifact.source','manifest.source','artifact.target','manifest.target')){Copy-Item (Join-Path $fx $n) (Join-Path $target $n)}
function Q([string]$v){'"'+$v.Replace('"','\"')+'"'}
function Invoke-Json([string[]]$a){$exe=Get-Command pwsh.exe -ErrorAction SilentlyContinue;if(!$exe){$exe=Get-Command powershell.exe};$args=@('-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',(Join-Path $h 'Invoke-MayaDeploymentV4.ps1'))+$a;$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$exe.Source;$psi.Arguments=($args|ForEach-Object{Q $_}) -join ' ';$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$psi.UseShellExecute=$false;$psi.EnvironmentVariables['REPATO_AGENT_STORE_PATH']=$store;$p=[Diagnostics.Process]::Start($psi);$so=$p.StandardOutput.ReadToEnd();$se=$p.StandardError.ReadToEnd();$p.WaitForExit();if($p.ExitCode -ne 0){throw $se};$j=@($so.Trim()|ConvertFrom-Json);if($j.Count -ne 1){throw 'Expected one JSON object.'};$j[0]}
try {
 $id='MAYA-V4-'+[guid]::NewGuid().ToString('N')
 New-RepatoTask $store $id $id deployment 'feat/maya-deployment-orchestration' maya | Out-Null
 Claim-RepatoTask $store $id Neil | Out-Null
 Update-RepatoTask $store $id 'in-progress' implementation Neil $null $null | Out-Null
 Update-RepatoTask $store $id 'in-progress' 'build-checks' Neil $null $null | Out-Null
 Update-RepatoTask $store $id passed qa Tara $null $null | Out-Null
 $base=@('-StoreRoot',$store,'-TaskId',$id,'-ArtifactPath',(Join-Path $target 'artifact.source'),'-ManifestPath',(Join-Path $target 'manifest.source'),'-TargetRoot',$target)
 $plan=Invoke-Json (@('-Operation','maya-deploy-plan')+$base)
 $req=Invoke-Json (@('-Operation','maya-deploy-request-approval','-WorkflowId',$plan.WorkflowId)+@('-StoreRoot',$store,'-TaskId',$id))
 $ap=Invoke-Json @('-Operation','maya-deploy-approve','-WorkflowId',$plan.WorkflowId,'-StoreRoot',$store,'-TaskId',$id)
 $approval=$ap.approvalId
 $val=Invoke-Json @('-Operation','maya-deploy-validate','-WorkflowId',$plan.WorkflowId,'-ApprovalId',$approval,'-StoreRoot',$store,'-TaskId',$id)
 $b=Invoke-Json @('-Operation','maya-deploy-backup','-WorkflowId',$plan.WorkflowId,'-ApprovalId',$approval,'-StoreRoot',$store,'-TaskId',$id)
 $a=Invoke-Json @('-Operation','maya-deploy-apply','-WorkflowId',$plan.WorkflowId,'-ApprovalId',$approval,'-StoreRoot',$store,'-TaskId',$id)
 $v=Invoke-Json @('-Operation','maya-deploy-verify','-WorkflowId',$plan.WorkflowId,'-ApprovalId',$approval,'-StoreRoot',$store,'-TaskId',$id)
 $c=Invoke-Json @('-Operation','maya-deploy-complete','-WorkflowId',$plan.WorkflowId,'-ApprovalId',$approval,'-StoreRoot',$store,'-TaskId',$id)
 $status=Invoke-Json @('-Operation','maya-deploy-status','-WorkflowId',$plan.WorkflowId,'-StoreRoot',$store,'-TaskId',$id)
 if($status.stage -ne 'completed'){throw 'Final stage mismatch.'}
 'Maya v4 CLI lifecycle checks passed: 9'
} finally { if(Test-Path $run){Remove-Item $run -Recurse -Force} }

# Apply failure subprocess scenario
$run=Join-Path ([IO.Path]::GetTempPath()) ('maya-v4-fail-'+[guid]::NewGuid().ToString('N'));$target=Join-Path $run 'target';$store=Join-Path $run 'store';New-Item $target -ItemType Directory -Force|Out-Null;$fx=Join-Path $h 'DeploymentFixtures';foreach($n in @('artifact.source','manifest.source','artifact.target','manifest.target')){Copy-Item (Join-Path $fx $n) (Join-Path $target $n)};try{$id='MAYA-V4-FAIL-'+[guid]::NewGuid().ToString('N');New-RepatoTask $store $id $id deployment 'feat/maya-deployment-orchestration' maya|Out-Null;Claim-RepatoTask $store $id Neil|Out-Null;Update-RepatoTask $store $id 'in-progress' implementation Neil $null $null|Out-Null;Update-RepatoTask $store $id 'in-progress' 'build-checks' Neil $null $null|Out-Null;Update-RepatoTask $store $id passed qa Tara $null $null|Out-Null;$base=@('-StoreRoot',$store,'-TaskId',$id,'-ArtifactPath',(Join-Path $target 'artifact.source'),'-ManifestPath',(Join-Path $target 'manifest.source'),'-TargetRoot',$target,'-FailureMode','Apply');$pl=Invoke-Json (@('-Operation','maya-deploy-plan')+$base);if($pl.failureMode -ne 'Apply'){throw 'FailureMode not persisted'};$rq=Invoke-Json (@('-Operation','maya-deploy-request-approval','-WorkflowId',$pl.WorkflowId)+@('-StoreRoot',$store,'-TaskId',$id));$aa=Invoke-Json @('-Operation','maya-deploy-approve','-WorkflowId',$pl.WorkflowId,'-StoreRoot',$store,'-TaskId',$id);$ap=Invoke-Json @('-Operation','maya-deploy-validate','-WorkflowId',$pl.WorkflowId,'-ApprovalId',$aa.approvalId,'-StoreRoot',$store,'-TaskId',$id);$bk=Invoke-Json @('-Operation','maya-deploy-backup','-WorkflowId',$pl.WorkflowId,'-ApprovalId',$aa.approvalId,'-StoreRoot',$store,'-TaskId',$id);try{Invoke-Json @('-Operation','maya-deploy-apply','-WorkflowId',$pl.WorkflowId,'-ApprovalId',$aa.approvalId,'-StoreRoot',$store,'-TaskId',$id)|Out-Null;throw 'Apply unexpectedly succeeded'}catch{}$st=Invoke-Json @('-Operation','maya-deploy-status','-WorkflowId',$pl.WorkflowId,'-StoreRoot',$store,'-TaskId',$id);$rb=Invoke-Json @('-Operation','maya-deploy-rollback','-WorkflowId',$pl.WorkflowId,'-ApprovalId',$aa.approvalId,'-StoreRoot',$store,'-TaskId',$id);if($rb.stage -ne 'failed'){throw 'Rollback not terminal failed'};'Maya v4 Apply-failure checks passed: 8'}finally{if(Test-Path $run){Remove-Item $run -Recurse -Force}}

# Verify failure subprocess scenario
$run=Join-Path ([IO.Path]::GetTempPath()) ('maya-v4-vfail-'+[guid]::NewGuid().ToString('N'));$target=Join-Path $run 'target';$store=Join-Path $run 'store';New-Item $target -ItemType Directory -Force|Out-Null;$fx=Join-Path $h 'DeploymentFixtures';foreach($n in @('artifact.source','manifest.source','artifact.target','manifest.target')){Copy-Item (Join-Path $fx $n) (Join-Path $target $n)};try{$id='MAYA-V4-VFAIL-'+[guid]::NewGuid().ToString('N');New-RepatoTask $store $id $id deployment 'feat/maya-deployment-orchestration' maya|Out-Null;Claim-RepatoTask $store $id Neil|Out-Null;Update-RepatoTask $store $id 'in-progress' implementation Neil $null $null|Out-Null;Update-RepatoTask $store $id 'in-progress' 'build-checks' Neil $null $null|Out-Null;Update-RepatoTask $store $id passed qa Tara $null $null|Out-Null;$base=@('-StoreRoot',$store,'-TaskId',$id,'-ArtifactPath',(Join-Path $target 'artifact.source'),'-ManifestPath',(Join-Path $target 'manifest.source'),'-TargetRoot',$target,'-FailureMode','Verify');$pl=Invoke-Json (@('-Operation','maya-deploy-plan')+$base);$rq=Invoke-Json (@('-Operation','maya-deploy-request-approval','-WorkflowId',$pl.WorkflowId)+@('-StoreRoot',$store,'-TaskId',$id));$aa=Invoke-Json @('-Operation','maya-deploy-approve','-WorkflowId',$pl.WorkflowId,'-StoreRoot',$store,'-TaskId',$id);$ap=Invoke-Json @('-Operation','maya-deploy-validate','-WorkflowId',$pl.WorkflowId,'-ApprovalId',$aa.approvalId,'-StoreRoot',$store,'-TaskId',$id);$bk=Invoke-Json @('-Operation','maya-deploy-backup','-WorkflowId',$pl.WorkflowId,'-ApprovalId',$aa.approvalId,'-StoreRoot',$store,'-TaskId',$id);$app=Invoke-Json @('-Operation','maya-deploy-apply','-WorkflowId',$pl.WorkflowId,'-ApprovalId',$aa.approvalId,'-StoreRoot',$store,'-TaskId',$id);try{Invoke-Json @('-Operation','maya-deploy-verify','-WorkflowId',$pl.WorkflowId,'-ApprovalId',$aa.approvalId,'-StoreRoot',$store,'-TaskId',$id)|Out-Null;throw 'Verify unexpectedly succeeded'}catch{}$st=Invoke-Json @('-Operation','maya-deploy-status','-WorkflowId',$pl.WorkflowId,'-StoreRoot',$store,'-TaskId',$id);$rb=Invoke-Json @('-Operation','maya-deploy-rollback','-WorkflowId',$pl.WorkflowId,'-ApprovalId',$aa.approvalId,'-StoreRoot',$store,'-TaskId',$id);if($rb.stage -ne 'failed'){throw 'Verify rollback not failed'};'Maya v4 Verify-failure checks passed: 8'}finally{if(Test-Path $run){Remove-Item $run -Recurse -Force}}
